Refactor/kotlin
Skatteetaten/aurora-gradle-plugin pull request #31
Opened 2020-08-31 08:53 UTC by mikand13

2020-08-31 09:05 UTC, bjartek commented on src/main/kotlin/no/skatteetaten/aurora/gradle/plugins/mutators/JavaApplicationTools.kt
> +                        "compileTestGroovy.classpath += files(compileTestKotlin.destinationDir)"
w: /Users/m89870/dev/test/aurora-gradle-plugin/src/main/kotlin/no/skatteetaten/aurora/gradle/plugins/mutators/JavaApplicationTools.kt: (367, 25): The expression is unused sier mitt bygg her.

2020-08-31 09:05 UTC, bjartek commented on src/main/kotlin/no/skatteetaten/aurora/gradle/plugins/mutators/JavaApplicationTools.kt
> +                    "attributes([ snippets: snippetsDir, version : version ])"
w: /Users/m89870/dev/test/aurora-gradle-plugin/src/main/kotlin/no/skatteetaten/aurora/gradle/plugins/mutators/JavaApplicationTools.kt: (476, 21): The expression is unused mitt bygg sier dette.

2020-08-31 09:10 UTC, bjartek requested changes
Jeg får beskjed om at 
w: /Users/m89870/dev/test/aurora-gradle-plugin/src/main/kotlin/no/skatteetaten/aurora/gradle/plugins/mutators/JavaApplicationTools.kt: (367, 25): The expression is unused
w: /Users/m89870/dev/test/aurora-gradle-plugin/src/main/kotlin/no/skatteetaten/aurora/gradle/plugins/mutators/JavaApplicationTools.kt: (476, 21): The expression is unused

stemmer dette eller er det noe feil i kompilatoren?

2020-08-31 09:40 UTC, jarlehansen requested changes

2020-08-31 09:40 UTC, jarlehansen commented on src/test/kotlin/no/skatteetaten/aurora/gradle/plugins/extensions/AuroraExtensionFunctionalKtsTest.kt
> +        assertThat(result.task(":build")?.outcome == SUCCESS).isTrue()
`assertThat(result.task(":build")?.outcome).isEqualTo(SUCCESS)`

2020-08-31 09:40 UTC, jarlehansen commented on src/test/kotlin/no/skatteetaten/aurora/gradle/plugins/extensions/AuroraExtensionFunctionalKtsTest.kt
> +        assertThat(result.task(":build")?.outcome == SUCCESS).isTrue()
`assertThat(result.task(":build")?.outcome).isEqualTo(SUCCESS)`

2020-08-31 09:40 UTC, jarlehansen commented on src/test/kotlin/no/skatteetaten/aurora/gradle/plugins/extensions/AuroraExtensionFunctionalKtsTest.kt
> +        assertThat(result.task(":build")?.outcome == SUCCESS).isTrue()
mye av det samme går igjen, hva med å lage en egen assert på `BuildResult`?

2020-08-31 09:40 UTC, jarlehansen commented on src/test/kotlin/no/skatteetaten/aurora/gradle/plugins/extensions/AuroraExtensionFunctionalKtsTest.kt
> +        assertThat(result.output.contains("no.skatteetaten.aurora.springboot:aurora-spring-boot-mvc-starter")).isFalse()
`assertThat(result.output).contains(...)`

2020-08-31 09:40 UTC, jarlehansen commented on src/test/kotlin/no/skatteetaten/aurora/gradle/plugins/functional/AuroraPluginFunctionalKtsTest.kt
> +@Execution(CONCURRENT)
Er alt konfigurert med concurrent? Da kan vi vel sette det i junit properties

2020-08-31 09:46 UTC, mikand13 commented on src/test/kotlin/no/skatteetaten/aurora/gradle/plugins/functional/AuroraPluginFunctionalKtsTest.kt
> +@Execution(CONCURRENT)
Alt er det foreløpig hvertfall, er speca i junit props ja, men denne setter concurrent internt i klassen. Den i props setter vel bare på class-nivå? 🤔 Jeg tester

2020-09-03 10:34 UTC, jarlehansen approved these changes

2020-09-03 10:34 UTC, jarlehansen commented on src/test/kotlin/no/skatteetaten/aurora/gradle/plugins/extensions/AuroraExtensionFunctionalKtsTest.kt
> +        result.taskStatus()
Dette er minor, men hva om taskStatus er en egen assert?

noe sånt:
```
fun Assert<BuildResult>.taskStatus(taskName: String = ":build", expected: TaskOutcome = TaskOutcome.SUCCESS) {
        prop("task.outcome") {
            it.task(taskName)?.outcome
        }.isEqualTo(expected)
    }
```

2020-09-03 11:55 UTC, mikand13 commented on src/test/kotlin/no/skatteetaten/aurora/gradle/plugins/extensions/AuroraExtensionFunctionalKtsTest.kt
> +        result.taskStatus()
Du tenker assertThat(result).taskStatus()?

2020-09-03 13:03 UTC, jarlehansen commented on src/test/kotlin/no/skatteetaten/aurora/gradle/plugins/extensions/AuroraExtensionFunctionalKtsTest.kt
> +        result.taskStatus()
stemmer

2020-09-03 16:14 UTC, mikand13 commented on src/test/kotlin/no/skatteetaten/aurora/gradle/plugins/extensions/AuroraExtensionFunctionalKtsTest.kt
> +        result.taskStatus()
Det kan jeg fikse 👌

2020-09-14 09:52 UTC, bjartek approved these changes

2020-09-17 07:29 UTC, merged